---
title: Creative Commons Indonesia
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
keywords: 
disqus:
  name: nama_disini
  public_key: public_key_disini
ga:
  id: ganalytic_disini
permalink: "/:year/:month/:title/"
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      